import random

class Messages:
    """Class to store Bot messages."""

    # Create a Dictionary with all Messages
    books = {
        "The Art of Laziness, by Library Mindset": [
            "Nunca vai haver um timing perfeito, portanto o melhor é começar já.",
            "Pomodoro Technique - Trabalhar durante 25 minutos e descansar 5.",
            "Se algo demorar menos de 5 minutos, é para ser feito imediatamente.",
            "Multitasking não resulta, é preferível fazer 1 coisa de cada vez.",
            "Aprender a dizer que não.",
            "Fazer as tarefas que odiamos primeiro.",
            "Fazer coisas que gostamos.",
            "Ler sobre tudo.",
            "Daqui a 20 anos, as únicas pessoas que se vã lembrar que trabalhaste até tarde vão ser os teus filhos, Sahil Bloom",
            "Nunca falhar em nada durante dois dias seguidos.",
            "Comer até ficar 80% cheio.",
            "Se uma decisão for reversível, toma-se a decisão o mais rápido possível, se for irreversível, toma-se o mais tardar possível, Shane Parris.",
        ],
        "Como falar com todos, by Leil Lowndes": [
            "TÉCNICA #1 O Sorriso Inundante — Não sorria imediatamente ao cumprimentar alguém. Em vez disso, olhe por um segundo, absorva a personalidade da pessoa, e só depois sorria de forma calorosa e recetiva.",
            "TÉCNICA #2 Olhos Pegajosos — Finja que os seus olhos estão colados aos do outro com caramelo quente. Mantenha o contacto visual mesmo após o fim da fala.",
            "TÉCNICA #3 Olhos de Resina — Observe a sua pessoa-alvo mesmo quando outra pessoa está a falar.",
            "TÉCNICA #4 Pendurado pelos Dentes — Visualize estar pendurado pelos dentes numa tenda de circo ao passar por portas. Isso melhora a sua postura.",
            "TÉCNICA #5 A Pirueta do Bebé Grande — Ao ser apresentado a alguém, vire-se totalmente para essa pessoa como se ela fosse um bebé adorável.",
            "TÉCNICA #6 Olá, Velho Amigo — Imagine que cada pessoa nova é um amigo há muito não visto. A sua linguagem corporal vai mudar automaticamente.",
            "TÉCNICA #7 Limitar a Inquietação — Em conversas importantes, controle qualquer impulso de se mexer ou coçar. Mãos longe da cara!",
            "TÉCNICA #8 O Sexto Sentido do Cavalo Hans — Esteja atento às reações do outro durante a conversa e ajuste-se a elas.",
            "TÉCNICA #9 Veja a Cena antes de a Executar — Visualize-se no seu melhor antes de interações sociais para que tudo aconteça naturalmente.",
            "TÉCNICA #10 Fazer Uma Correspondência de Ânimo — Identifique o estado emocional da pessoa antes de falar, e ajuste o seu tom e energia.",
            "TÉCNICA #11 Prosaico com Paixão — O que importa não são as palavras, mas a forma apaixonada como as diz.",
            "TÉCNICA #12 Use sempre Um Queéisso — Vista ou leve algo curioso para ser um ponto de partida de conversa.",
            "TÉCNICA #13 Queméaquele — Peça ao anfitrião para lhe apresentar alguém, ou recolha informação útil para quebrar o gelo.",
            "TÉCNICA #14 Bisbilhotar a Conversa — Fique por perto, ouça e entre com um comentário como “Desculpe, não pude deixar de ouvir…”",
            "TÉCNICA #15 A Cidade Nua nunca — Não diga só de onde é. Dê factos interessantes que estimulem a conversa.",
            "TÉCNICA #16 O Trabalho Nu nunca — Não diga só a profissão. Descreva-a de forma interessante para gerar conversa.",
            "TÉCNICA #17 A Apresentação Nua nunca — Ao apresentar duas pessoas, dê um tópico de conversa inicial.",
            "TÉCNICA #18 Seja Um Detetive de Palavras — Ouça pistas nas palavras do outro para saber do que ele gosta de falar.",
            "TÉCNICA #19 O Holofote Giratório — Faça com que o outro brilhe, e ele vai achar que você é fascinante.",
            "TÉCNICA #20 Papaguear — Repita as últimas palavras da outra pessoa para manter a conversa fluida.",
            "TÉCNICA #21 Encore! O som mais doce que um artista pode ouvir a brotar do meio dos aplausos é «Encore! Encore! Cante de novo!». O som mais doce que o interlocutor pode ouvir dos seus lábios quando está a conversar com um grupo de pessoas é: «Conta-lhes aquela história de quando tu…» Sempre que estiver numa reunião ou numa festa com alguém importante para si, pense em algumas histórias que ele ou ela lhe contou. Escolha a mais apropriada do repertório de que o público possa gostar. Em seguida, aponte-lhe os holofotes e solicite-lhe uma repetição do desempenho.",
            "TÉCNICA #22 A-cen-tue-a-Parte-Po-si-ti-va Quando conhecer alguém, tranque a porta do armário e guarde os seus esqueletos para mais tarde. O leitor e o seu novo bom amigo podem convidar os esqueletos a sair, dar boas gargalhadas e dançar sobre os ossos mais tarde. No entanto, agora é a altura, como diz a canção, de «Acentuar a parte positiva e eliminar a negativa».",
            "TÉCNICA #23 As Últimas Notícias… não Saia de Casa sem Elas O último movimento que fazer antes de sair para a festa — mesmo depois de ter dado uma última olhadela ao espelho — é sintonizar o noticiário no rádio ou ler o jornal. Tudo o que aconteceu hoje é bom material. Saber as notícias mais importantes do momento é também uma ação defensiva que o salva de meter o pé na argola e perguntar de que é que toda gente está a falar. Meter o pé na argola não é um movimento muito elegante em público, especialmente quando a argola está numa poça de lama.",
            "TÉCNICA #24 O Currículo Resumido Tal como os gestores de topo em busca de emprego tiram um currículo escrito diferente da impressora para cada posição para a qual se candidatam, conte uma história real diferente sobre a sua vida profissional a cada ouvinte. Antes de responder à pergunta sobre o que faz, pergunte a si mesmo: «Que possível interesse pode esta pessoa ter na minha resposta? Será que pode trazer-me novos negócios? Comprar-me produtos? Contratar-me? Casar-se com a minha irmã? Tornar-se minha amiga?» Aonde quer que vá, ponha um resumo da sua própria vida na mala de truques de comunicação.",
            "TÉCNICA #25 O Currículo Resumido Tal como os gestores de topo em busca de emprego tiram um currículo escrito diferente da impressora para cada posição para a qual se candidatam, conte uma história real diferente sobre a sua vida profissional a cada ouvinte. Antes de responder à pergunta sobre o que faz, pergunte a si mesmo: «Que possível interesse pode esta pessoa ter na minha resposta? Será que pode trazer-me novos negócios? Comprar-me produtos? Contratar-me? Casar-se com a minha irmã? Tornar-se minha amiga?»",
            "TÉCNICA #26 O Seu Dicionário de Sinónimos Pessoal Procure algumas das palavras habituais que usa todos os dias no dicionário de sinónimos. Então, tal como enfiar os pés num novo par de sapatos, faça a língua deslizar por algumas palavras novas para ver como se encaixam. Se gostar delas, comece a fazer substituições permanentes. Lembre-se de que apenas cinquenta palavras fazem a diferença entre um vocabulário rico e criativo e um vocabulário intermédio. Substitua uma palavra por dia durante dois meses e estará na elite verbal.",
            "TÉCNICA #27 «Mate o “Eu também” Imediato!» Sempre que tiver algo em comum com alguém, quanto mais esperar para o revelar, mais comovida (e impressionada) a pessoa ficará. O leitor surge como um gatarrão confiante e não um gato vadio solitário, faminto por uma conexão rápida com um estranho. P. S.: Não espere muito para revelar o seu interesse comum ou parecerá dissimulado.",
            "TÉCNICA #28 Comunicação VOCÊ Comece cada frase apropriada na terceira pessoa (você). Isto chama imediatamente a atenção do seu ouvinte e proporciona-lhe uma resposta mais positiva, porque prime o botão do orgulho e evita que eles tenham de traduzir a pergunta em termos de «eu». Quando espalha o você tão liberalmente como sal e pimenta na conversa, os seus interlocutores acham-no um tempero irresistível.",
            "TÉCNICA #29 O Sorriso Exclusivo Se mostrar a todos o mesmo sorriso, ele perde valor, tal como um dólar confederado. Ao conhecer grupos de pessoas, ofereça a cada uma delas um sorriso distinto. Deixe que os seus sorrisos nasçam da beleza que os grandes jogadores encontram em cada novo rosto. Se uma pessoa num grupo é mais importante para si do que as outras, reserve um sorriso especialmente grande e expansivo apenas para ela.",
            "TÉCNICA #30 Mantenha os Lugares-Comuns a Distância Esteja alerta. Não use lugares-comuns quando conversar com grandes vencedores. Não se aproxime sequer de um. Nunca? Nem que chovam picaretas? Não, a menos que queira parecer estúpido que nem uma porta. Em vez de dizer um lugar-comum, crie as suas próprias frases inteligentes usando a técnica seguinte.",
            "TÉCNICA #31 Use a Dança do Demagogo Quer esteja de pé atrás de um pódio diante de milhares de pessoas ou atrás do grelhador diante da sua família, irá emocionar, divertir e motivar com as mesmas capacidades. Leia livros de oradores para recolher citações, extrair pérolas de sabedoria e obter joias para divertir os outros. Encontre alguns bon mots para deixar escapar casualmente em ocasiões especiais. Se quer ser notável, invente uma citação maluca. Faça-as rimar, torne-as inteligentes ou engraçadas. Acima de tudo, torne-as relevantes.",
            "TÉCNICA #32 Chame os Bois pelos Nomes Não se esconda atrás de eufemismos. Chame os bois pelos nomes. Isso não significa que os gatarrões usem palavrões rudes quando existem palavras correntes perfeitamente decentes. Simplesmente, aprenderam o português correto e falam-no. Esta é outra maneira de diferenciar os grandes jogadores dos juniores; basta ouvir apenas alguns minutos das conversas deles.",
            "TÉCNICA #33 Arrase a Provocação Uma pista clara de que alguém é um gatinho é a tendência a provocar. Uma piada inocente à custa de outra pessoa pode render-lhe uma gargalhada fácil. No entanto, os gatarrões rir-se-ão por último, porque o leitor baterá com a cabeça no teto de vidro que constroem para evitar que os gatinhos os pisem. Nunca, jamais, faça uma piada à custa de outra pessoa. Acabará a pagar por ela, bastante.",
            "TÉCNICA #34 Um jogador de futebol não duraria dois segundos em campo se fizesse passes às cegas. Um profissional chuta a bola sempre com o recetor em mente. Antes de lançar qualquer notícia, lembre-se de quem as recebe. Em seguida, dê as notícias com um sorriso, um suspiro ou um soluço. Não de acordo com o que o leitor sente sobre as notícias, mas com o modo como o recetor as vai receber.",
            "TÉCNICA #35 O Disco Riscado Sempre que alguém persistir em o interrogar sobre um assunto indesejável, repita simplesmente a resposta original. Use exatamente as mesmas palavras, no mesmo tom de voz. Ouvir a mesma coisa de novo fá-los geralmente calar-se. Se o seu interrogador rude se agarrar como uma sanguessuga, a sua repetição seguinte nunca falha em silenciá-lo.",
            "TÉCNICA #36 Os Grandes Vencedores não Se Babam As pessoas VIP por direito próprio não se babam perante celebridades. Quando estiver a conversar com uma, não lhe elogie o trabalho; em vez disso, diga simplesmente que lhe deu muito prazer ou que o fez pensar. Se destacar algum dos trabalhos da estrela, certifique-se de que é um trabalho recente e não uma memória que fica amarelada no livro de recortes. Se a abelha-rainha tem um zangão sentado com ela, encontre uma maneira de o envolver na conversa.",
            "TÉCNICA #37 O Obrigado Despido nunca - Nunca deixe a palavra «obrigado» sozinha. De A a Z, acompanhe-a sempre. De um «Obrigado por aceitares» a um «Obrigado por zelares por mim».",
            "TÉCNICA #38 Terapia de Embaralhar - Uma vez por mês, embaralhe a sua vida. Faça algo que nunca sonhou fazer. Participe num desporto, vá a uma exposição, ouça uma palestra sobre algo totalmente fora da sua experiência. O leitor obtém oitenta por cento do jargão correto e das perguntas conhecedoras com apenas uma exposição.",
            "TÉCNICA #39 Aprenda um pouco de Algaraviada Profissional - Os grandes vencedores falam Algaraviada Profissional como segunda língua. Que é a Algaraviada Profissional? É a linguagem das outras profissões. Porquê falá-la? Porque fá-lo parecer um insider. Como a aprende? Não vai encontrar cassetes de Algaraviada Profissional na secção de línguas estrangeiras da sua livraria, mas é uma língua fácil de apanhar. Basta pedir a um amigo que fala o jargão do grupo com quem o leitor vai estar que lhe ensine algumas perguntas iniciais. As palavras são poucas e as recompensas são múltiplas.",
            "TÉCNICA #40 Revelar o Ponto Quente Deles Antes de avançar às cegas para um bando de encadernadores ou colmeia de dentistas, descubra quais são os temas quentes nas áreas deles. Cada setor tem grandes preocupações sobre as quais o mundo exterior pouco sabe. Peça ao seu informador que revele o tema quente do setor. Então, para aquecer a conversa, prima esses botões.",
            "TÉCNICA #41 Leia as Revistas Deles: O seu próximo grande cliente é jogador de golfe, corredor, nadador, surfista ou esquiador? Vai participar num evento social repleto de contabilistas ou budistas zen — ou algo entre esses dois extremos? Existem incontáveis milhares de revistas mensais sobre todos os interesses imagináveis. Pode obter mais informações do que as de que precisa para soar como um insider junto de qualquer pessoa lendo simplesmente as revistas que servem os interesses delas. (Já leu o último número da Zoonooz?)",
            "TÉCNICA #42 «Alfândega» Livre: Antes de pôr um pé em solo estrangeiro, leia um livro sobre o que pode fazer e quais os tabus ao redor do mundo. Antes de apertar as mãos, dar um presente, fazer gestos ou até elogiar os pertences de alguém, verifique. A sua gafe pode atrapalhar todo o seu trabalho.",
            "TÉCNICA #43 Enganar para Conseguir Pechinchas: As habilidades de pechinchar usadas nos antigos mercados árabes estão vivas e de boa saúde nos EUA contemporâneos para artigos caros. O seu preço é muito mais baixo quando sabe como negociar. Antes de cada grande compra, procure vários fornecedores — alguns para aprender e um para comprar. Armado com algumas palavras do idioma da indústria, está pronto para ir à loja onde vai comprar.",
            "TÉCNICA #44 Seja Copiador de Classe: Observe as pessoas. Veja como se movem. Movimentos pequenos? Movimentos grandes? Rápido? Lento? Espasmódico? Fluido? Velho? Novo? Elegante? Rasca? Finja que a pessoa com quem está a falar é o seu instrutor de dança. Será que ele tem movimentos de jazz? Será que ela tem movimentos de balé? Observe o seu corpo e, de seguida, imite o estilo de movimentos. Isso faz o seu parceiro de conversa sentir-se subliminarmente confortável consigo.",
            "TÉCNICA #45 Ecoar: Ecoar é uma técnica linguística simples que tem grande impacto. Ouça a escolha arbitrária de substantivos, verbos, preposições, adjetivos de quem fala e faça eco dela. Quando eles ouvem as suas próprias palavras a sair-lhe da boca, isso cria um relacionamento subliminar. Fá-los sentir que o leitor partilha os seus valores, as suas atitudes, os seus interesses e as suas experiências.",
            "TÉCNICA #46 Imagem Potente: O seu cliente tem um jardim? Fale-lhe de «plantar as sementes do sucesso». O seu chefe tem um barco? Fale-lhe de um conceito que irá «enfrentar as ondas» ou «manter-se à tona». Talvez ele seja piloto privado. Fale de um conceito que está mesmo a «levantar voo». Ela joga ténis? Diga-lhe que a situação bateu mesmo «na linha». Evoque os interesses ou estilo de vida do seu ouvinte e crie imagens em torno disso. Para dar aos seus pontos mais força e impacto, use analogias do mundo do seu ouvinte e não do seu. A Imagem Potente também diz aos ouvintes que o leitor pensa como eles e sugere que partilha os mesmos interesses.",
            "TÉCNICA #47 Empregue Palavras de Empatia: Não seja murmurador inconsciente. Vocalize frases completas para mostrar a sua compreensão. Salpique o diálogo com frases como «Percebo o que quer dizer» ou polvilhe-o com faíscas sentimentais como «Isso foi muito simpático da sua parte». A sua empatia impressiona os ouvintes e incentiva-os a continuar.",
            "TÉCNICA #48 Empatia anatomicamente Correta: Com que parte da anatomia estão os seus colegas a falar? Com os olhos? Os ouvidos? As entranhas? Para pessoas visuais, use palavras de empatia visual para as fazer pensar que vê o mundo do mesmo modo que elas. Para as pessoas auditivas, use palavras de empatia auditivas para as fazer pensar que as ouviu alto e bom som. Para os tipos cinestésicos, use palavras de empatia cinestésicas para os fazer pensar que se sente da mesma maneira que eles.",
            "TÉCNICA #49 O Nós Prematuro: Crie a sensação de intimidade com alguém, mesmo que se tenham conhecido há apenas alguns instantes. Baralhe os sinais na psique dele, saltando os níveis de conversação um e dois e indo diretamente para os níveis três e quatro. Incite sentimentos íntimos usando as palavras mágicas nós, nos e nosso.",
            "TÉCNICA #50 História Instantânea: Quando conhecer um estranho que gostaria de tornar menos estranho, procure algum momento especial que tenham partilhado durante o vosso primeiro encontro. Depois, encontre algumas palavras que recordem o riso, o sorriso caloroso, os bons sentimentos que tenham ambos sentido. Agora, tal como velhos amigos, têm uma história juntos, uma História Instantânea. Procure os momentos especiais que tenha tido com qualquer pessoa que gostaria de que fizesse parte do seu futuro pessoal ou profissional. Depois, transforme-os num refrão.",
            "TÉCNICA #51 A Glória dos Rumores: Um elogio que nos é dito nunca é tão emocionante como aquele que ouvimos por terceiros. Uma forma inestimável de elogiar não é por telefone, nem por telégrafo, mas contando a um amigo. Desta forma, escapa à possível suspeita de que é um bajulador que está a dar graxa, palmadinhas nas costas ou a lamber botas para tentar ganhar pontos. Também deixa os destinatários com a feliz fantasia de que anda a falar a todos da grandeza deles.",
            "TÉCNICA #52 Cumprimentos do Pombo-Correio: As pessoas ganham imediatamente um bico e metamorfoseiam-se em pombos-correio quando há más notícias. (Chama-se coscuvilhice.) Em vez disso, torne-se portador de boas notícias e cumprimentos. Sempre que ouvir algo elogioso sobre alguém, transporte o elogio até essa pessoa. Os seus fãs podem não o empalhar postumamente e exibi-lo num museu como a Stumpy Joe, mas toda a gente adora o pombo-correio de pensamentos bondosos.",
            "TÉCNICA #53 Magnificência Implícita: Introduza alguns comentários na conversa que pressuponham algo positivo sobre a pessoa com quem está a falar. Mas tenha cuidado. Não estrague tudo como o bem-intencionado homem da manutenção. Ou como o rapaz que no baile de formatura achou que estava a elogiar o seu par quando lhe disse: «Caramba, Mary Lou, para uma miúda gorda, danças muito bem.»",
            "TÉCNICA #54 Adulação Acidental: Torne-se um elogiador disfarçado. Inclua furtivamente elogios na parte entre parênteses da sua frase. No entanto, não tente questionar ninguém mais tarde sobre o seu ponto principal. O alegre choque da adulação acidental deixa-os temporariamente surdos a tudo o que se seguir.",
            "TÉCNICA #55 Elogio Arrasador: Sempre que estiver a conversar com um estranho que gostaria de que fizesse parte do seu futuro profissional ou pessoal, procure uma qualidade atraente, específica e única que essa pessoa tenha. No final da conversa, fite a pessoa mesmo nos olhos. Diga o nome dele ou dela e faça-o estremecer de felicidade com o Elogio Arrasador.",
            "TÉCNICA #56 Pequenos Toques: Não faça os seus colegas, amigos e entes queridos olhar para si e dizer silenciosamente: «Será que não fui muito bom hoje?» Deixe-os saber quanto os aprecia, acariciando-os com pequenos toques verbais como «Bom trabalho!», «Muito bem!» e «Ótimo!».",
            "TÉCNICA #57 O «Uau!» Reativo: Rápido como um piscar de olhos, deve elogiar as pessoas no momento em que concluem um feito. Num piscar de olhos, como uma reação automática, diga: «Foste incrível!» Não se preocupe se não acreditarem em si. A euforia do momento tem um efeito estranhamente entorpecedor no julgamento objetivo do executante.",
            "TÉCNICA #58 Fazer Bumerangue: Tal como um bumerangue voa de volta para o ponto inicial quando o lança, os seus elogios devem regressar diretamente a você. Se os seu bumerangues de elogio o atingir, tudo o que precisa fazer é devolvê-los e ouvir um agradecimento sincero. Além disso, use essas palavras de elogio em tempo oportuno.",
            "TÉCNICA #59 Suavizar as Reticências: Ao final de uma conversa, deixe claro que o processo não está completo. Um simples gesto, como jogar suavemente a frase «Diga-me, vou voltar mais tarde» ou um sorriso significando que os seus ouvidos não se encerraram.",
            "TÉCNICA #60 Gestos Falantes: Pense em si como a estrela de um drama de rádio pessoal sempre que pegar no telefone. Se quiser fazer transparecer a sua simpatia, tem de transformar os sorrisos em sons, os acenos em ruído e todos os gestos em algo que o ouvinte possa ouvir. Tem de substituir os gestos por conversa, portanto, reforce toda a atuação trinta por cento!",
            "TÉCNICA #61 Regar com o Nome: As pessoas animam-se quando ouvem o próprio nome. Use-o com mais frequência ao telefone do que pessoalmente para lhes prender a atenção. O nome do seu interlocutor recria o contacto visual, a carícia que poderia dar pessoalmente. Dizer repetidamente o nome de alguém cara a cara soa a bajulação. Contudo, porque existe distância física entre vocês ao telefone — às vezes, estão a um continente de distância —, pode salpicar o nome da pessoa na conversa.",
            "TÉCNICA #62 «Oh, ainda bem que é você!» Não atenda o telefone com uma atitude de «Estou tão feliz o tempo todo». Atenda calorosamente, com firmeza e profissionalmente. Então, depois de saber quem está a ligar, deixe um enorme sorriso de felicidade engolir-lhe todo o rosto e transbordar-lhe na voz. Assim, faz o seu interlocutor sentir que o seu sorriso gigante e caloroso está reservado apenas para ele ou para ela.",
            "TÉCNICA #63 O Filtro Enganador: Se precisar de filtrar as chamadas, instrua a sua equipa a dizer primeiro alegremente: «Ah, sim, vou transferi-lo imediatamente. Pode dizer-me quem fala?» Se a pessoa já se identificou, diga: «Oh, claro, Sr. Fulano. Vou passar imediatamente a chamada.» Quando a secretária voltar com a má notícia de que o Sr. ou a Sra. Mandachuva não está disponível, as pessoas não se ofendem e nunca se sentem filtradas. São sempre enganadas, tal como eu.",
            "TÉCNICA #64 Cumprimentar o Cônjuge: Sempre que ligar para a casa de alguém, identifique e cumprimente sempre a pessoa que atende. Sempre que ligar para o escritório de alguém mais de uma ou duas vezes, faça amizade com a secretária. Qualquer pessoa que esteja perto o suficiente para atender o telefone está perto o suficiente para influenciar a opinião do VIP sobre si.",
            "TÉCNICA #65 Qual É a Cor do Seu Tempo: Não importa quão urgente considere a sua chamada, comece sempre por perguntar à pessoa se é boa altura. Use o dispositivo Qual É a Cor do Seu Tempo? ou pergunte simplesmente se é um momento conveniente para falarem. Quando pergunta primeiro à pessoa se tem tempo, o leitor nunca colocará a sua patorra mesmo no meio das areias do tempo do parceiro telefónico. E nunca receberá um «Não!» apenas porque não era a altura certa.",
            "TÉCNICA #66 Mensagem em Constante Mudança: Se deseja ser considerada uma pessoa responsável e fiável, deixe uma saudação curta, profissional e simpática como mensagem. Nada de música. Nada de piadas. Nada de mensagens inspiradoras. Nada de alaridos, arrebiques ou extras. E eis o segredo: mude-a todos os dias. A sua mensagem não precisa de ser perfeita. Uma pequena tosse ou uma ligeira gaguez dá um toque de realidade encantador e despretensioso à sua mensagem.",
            "TÉCNICA #67 A Sua Audição de Dez Segundos: Enquanto marca o número, pigarreie para limpar a garganta. Se o gravador de chamadas atender, finja que o bipe é um grande produtor da Broadway a dizer «Próximo!». Agora, está ao vivo. Esta é A Sua Audição de Dez Segundos para provar que merece uma chamada de volta.",
            "TÉCNICA #68 A Escapadela ah, sim: Em vez de usar o nome da pessoa, diga casualmente o pronome ele ou ela. Esqueça o «Hum, posso falar com a Sra. Mandachuva, por favor?». Em vez disso, basta anunciar: «Olá. Fala Bob Smith. Ela está?» Atirar o ela familiar indica à secretária que você e a chefe dela são velhos amigos.",
            "TÉCNICA #69 «Estou a Ouvir a Sua Outra Linha»: Quando ouvir um telefone de fundo, pare de falar — a meio da frase, se necessário — e diga: «Estou a ouvir a sua outra linha» (ou o seu cão a ladrar, o seu bebé a chorar, o seu marido a ligar-lhe). Pergunte se ela precisa de tratar da situação. Quer precise ou não, ela perceberá que o leitor é um grande comunicador só por perguntar.",
            "TÉCNICA #70 Repetição Instantânea: Grave todas as conversas de negócios e ouça-as novamente. Na segunda ou terceira vez, consegue captar subtilezas significativas que perdeu na primeira vez. É como os adeptos de futebol, que muitas vezes não sabem se houve um passe falhado até verem tudo de novo na repetição.",
            "TÉCNICA #71 Mastigar ou Socializar: Os políticos querem estar cara a cara e olhos nos olhos com os eleitores. Como qualquer grande vencedor bem versado na ciência da proxémica e das relações espaciais, sabem que qualquer objeto, exceto a fivela do cinto, tem o efeito de uma parede de tijolos entre duas pessoas. Portanto, nunca têm comida ou bebida nas mãos numa festa. Venha para mastigar ou para socializar, mas não espere fazer as duas coisas. Como um bom político, coma antes de vir.",
            "TÉCNICA #72 Examinar a Sala: Quando chegar à reunião, pare dramaticamente à porta. Depois, examine d-e-v-a-g-a-r a situação. Deixe que os seus olhos viajem de um lado para o outro como uma equipa de Forças Especiais preparada para, num piscar de olhos, eliminar qualquer coisa que se mexa.",
            "TÉCNICA #73 Seja Quem Escolhe, não o Escolhido: O amigo de longa data, o amor da sua vida ou o contacto comercial que transformará o seu futuro podem não estar na festa. No entanto, algum dia, em algum sítio, ele ou ela estará. Faça de cada festa um ensaio para o grande evento. Não fique parado à espera do momento em que aquela pessoa especial vai aproximar-se de si. Faça-o acontecer explorando cada rosto na sala. Chega de «ficar a ver navios». Agarre o quê ou quem quiser ter na sua vida.",
            "TÉCNICA #74 Mãos Sedutoras: Seja um íman humano em vez de um repelente humano. Quando estiver numa reunião, ponha o seu corpo numa posição aberta — especialmente, os braços e as mãos. As pessoas gravitam instintivamente em direção às palmas das mãos abertas e aos pulsos sedutoramente dispostos na posição de «venha cá» e fogem dos nós dos dedos na posição de «despareça ou dou-lhe um soco». Use os pulsos e as palmas das mãos para dizer que não tem nada que esconder, que aceita o outro e aquilo que ele está a dizer ou que o acha atraente.",
            "TÉCNICA #75 Rastreamento: Como um controlador de tráfego aéreo, rastreie os mais pequenos detalhes da vida dos seus interlocutores. Introduza-os na sua conversa como se fosse um assunto importante. Isso cria uma poderosa sensação de intimidade. Quando invoca o último acontecimento importante ou secundário na vida de alguém, confirma a profunda convicção de que ele ou ela é um herói à moda antiga em torno do qual o mundo gira. E as pessoas adoram-no por lhes reconhecer o estrelato.",
            "TÉCNICA #76 O Dossiê dos Cartões-de-Visita: Assim que acabar de falar com alguém numa festa, pegue na sua caneta. No verso do cartão-de-visita da pessoa, escreva umas notas para o recordarem da conversa: o restaurante, o desporto, o filme ou a bebida favorita da pessoa; quem ela admira, onde cresceu, um prémio escolar; ou talvez uma piada que tenha contado. Na comunicação seguinte, introduza uma referência ao restaurante, ao desporto, ao filme ou à bebida favorita da pessoa, à sua cidade natal ou ao prémio escolar. Ou recorde as gargalhadas por causa da excelente piada dela.",
            "TÉCNICA #77 Vender com os Olhos: O corpo humano é uma estação emissora que transmite os programas «Entusiasmas-me», «Aborreces-me», «Adoro esse aspeto do teu produto» ou «Aquele põe-me a dormir» vinte e quatro horas por dia. Ponha câmaras ocultas atrás dos olhos para captar os sinais de todos os seus clientes e amigos. A seguir, planeie o argumento de vendas e o ritmo de acordo com aquilo que captar.",
            "TÉCNICA #78 Não Veja os Tropeços, não Ouça os Tropeços: Os comunicadores calmos permitem aos amigos, colegas, conhecidos e entes queridos o mito agradável de estarem acima dos tropeços comuns e funções biológicas embaraçosas. Simplesmente, não notam os pequenos derramamentos, escorregões, atrapalhamentos e gafes dos camaradas e ignoram obviamente os arrotos e todos os outros sinais de fragilidade humana dos companheiros mortais. Os grandes vencedores nunca ficam boquiabertos perante as gafes dos outros.",
            "TÉCNICA #79 Dar Uma Linguazinha: Sempre que a história de alguém é abortada, deixe a interrupção desenrolar-se. Dê a todos tempo para idolatrar o bebezinho, fazer o pedido ou apanhar os cacos. Então, quando o grupo se recompuser, diga simplesmente à pessoa que sofreu a interrupção na história: «Estava a contar uma história»; ou, melhor ainda, lembre-se de onde ela estava e pergunte: «Então, que aconteceu depois de…» (e preencha com as últimas palavras).",
            "TÉCNICA #80 Desvende o QPGCI Escondido: Sempre que sugerir uma reunião ou pedir um favor, divulgue os respetivos benefícios. Revele o que o leitor e a outra pessoa podem ganhar com isso, mesmo que não seja nada. Se mais tarde surgir algum benefício oculto, será considerado um espertalhão dissimulado.",
            "TÉCNICA #81 Deixe-os Saborear o Favor: Sempre que um amigo concordar em fazer-lhe um favor, dê tempo a esse seu amigo generoso para saborear a alegria da beneficência antes de o fazer sofrer as consequências. Quanto tempo? Pelo menos, vinte e quatro horas.",
            "TÉCNICA #82 Uma Mão Lava (Espere… Espere) a Outra: Quando faz um favor a alguém e é óbvio que essa pessoa «fica em dívida para consigo», espere um tempo adequado antes de lhe pedir que «pague». Deixe que a pessoa desfrute do facto (ou da ficção) de que o leitor fez isso por amizade. Não peça que a pessoa lhe lave a mão em pagamento demasiado depressa.",
            "TÉCNICA #83 As Festas São para Tagarelar: Existem três refúgios sagrados na selva humana, onde até o tigre mais duro sabe que não deve atacar. O primeiro deles são as festas. As festas são para as pessoas se divertirem e para criar bom companheirismo, não para confrontos. Os grandes jogadores sorriem e acenam com a cabeça, mesmo quando estão ao lado dos inimigos à mesa do bufê. Deixam as conversas difíceis para outros locais.",
            "TÉCNICA #84 O Jantar É para Comer: O refúgio seguro mais bem guardado e respeitado pelos grandes vencedores é a mesa de jantar. O momento de comerem juntos é um momento em que não abordam assuntos desagradáveis. Enquanto comem, sabem que não há nenhum problema em fazerem brainstorm juntos e discutirem o lado positivo do negócio: os sonhos, desejos, projetos. Podem trocar ideias livremente e apresentar novas sugestões. Mas nada de discussões difíceis.",
            "TÉCNICA #85 Os Encontros Casuais São para Palavras de Circunstância: Se está a vender, a negociar ou envolvido em qualquer comunicação delicada com alguém, NÃO tente lucrar sobre um encontro casual. Mantenha a melodia do encontro ocasional doce e leve. Caso contrário, pode transformar-se no seu canto de cisne junto do Grande Vencedor.",
            "TÉCNICA #86 Esvazie os Tanques Deles: Se precisar de informações, deixe que as pessoas digam primeiro o que têm para dizer. Espere pacientemente até que o ponteiro diga que o tanque esvaziou e a última gota pingue e caia no cimento. É a única maneira de ter a certeza de que o tanque delas está vazio o suficiente do próprio ruído interno para começar a receber as suas ideias.",
            "TÉCNICA #87 Ecoe o Emo: Os factos falam, as emoções gritam. Sempre que precisar de que as pessoas lhe deem factos sobre uma situação emocional, deixe-as emocionar-se. Ouça os factos delas, mas tenha enorme empatia pelas emoções. Carregar no emo é geralmente a única maneira de acalmar a tempestade emocional.",
            "TÉCNICA #88 Erro Meu, Ganho Seu: Sempre que cometer um erro, certifique-se de que a vítima beneficia. Corrigir o erro não é suficiente. Pergunte a si mesmo o que pode fazer por aquela alma sofredora para que ela fique encantada por ter cometido um erro e, então, faça-o, rapidamente! Dessa forma, o seu erro tornar-se-á o seu ganho.",
            "TÉCNICA #89 Crie Uma Escapatória: Sempre que apanhar alguém a mentir, roubar, exagerar, distorcer ou enganar, não enfrente o malandro diretamente. A menos que a sua responsabilidade seja apanhar ou corrigir o culpado — ou a menos que esteja a salvar outras vítimas inocentes se o apanhar —, deixe o transgressor sair da armadilha com o prestígio intacto. Depois, decida nunca mais lhe pôr os olhos em cima.",
            "TÉCNICA #90 Creme Gordo para o Chefe Deles: O leitor tem um empregado de loja, contabilista, sócio júnior de um escritório de advocacia, alfaiate, mecânico de automóveis, empregado de restaurante, terapeuta de massagens, professor de um filho ou qualquer outro funcionário de quem deseja obter atenção especial no futuro? A maneira infalível de os fazer importar-se o suficiente para se esforçarem ao máximo é enviar um creme gordo ao chefe deles.",
            "TÉCNICA #91 Lidere os Ouvintes: Não importa quão proeminente seja o mandachuva atrás do pódio, encolhido dentro dele está um gatinho assustado ansioso pela aceitação da multidão. Os grandes vencedores reconhecem que o leitor também é um grande vencedor quando o veem liderar a audiência com uma reação positiva. Seja o primeiro a aplaudir ou a elogiar publicamente o homem ou a mulher com quem concorda (ou de quem deseja favores).",
            "TÉCNICA #92 O Grande Quadro da Pontuação no Céu Quaisquer duas pessoas têm um placar invisível a pairar-lhes sobre as cabeças. Os números mudam continuamente, mas uma regra permanece: o jogador com a pontuação mais baixa presta deferência ao jogador com a pontuação mais alta. A penalidade por não estar atento ao Grande Quadro da Pontuação no Céu é ser expulso do jogo. Permanentemente."
        ],
        "Paris é uma Festa, by Ernest Hemingway":[
            "Quando renunciei a tudo isso. senti-me satisfeito, embora essa renúncia abrisse um vazio dentro de mim. Por essa altura. já eu sabia que tudo na vida — seja bom ou mau — nos provoca um vazio sempre que se acaba. No entanto, se a coisa fosse má, o tal vazio enchia-se por si próprio. Se fosse boa. só algo de melhor o poderia preencher. Transferi o capital das corridas para os fundos gerais e então senti-me aliviado e bom como uma criatura decente.",
        ],
    
    }


    def chooseMessage(self):
        """ Chooses a random message from a random Book """
        
        #Randomly chooses a random book
        book = random.choice(list(self.books.keys()))

        #Randomly chooses a message from a random book
        message = random.choice(list(self.books[book]))

        return f"'{message}'\n{book}"



